carolyn2004/devops-assignment

src/main/java/com/dvops/maven/eclipse/ReviewServlet.java
src/main/webapp/gameById.jsp

- Created a ReviewServlet to handle the request from the review web form.
- Added additional form fields in review form.
- Additional form fields include game name (hidden) and username.

[feat](game-review): Made add a review functional with database

---

src/main/java/com/dvops/maven/eclipse/LoginServlet.java
src/main/java/com/dvops/maven/eclipse/ReviewServlet.java
src/main/webapp/gameById.jsp

- Stored logged in user's username in login servlet.
- Retrieved logged in user's username in review servlet..
- Passed the username attribute from review servlet to review page.
- Called username attribute in review form so that we know which user wrote the review.
- Username field is hidden so user cannot alter/change username.

[feat](game-review): Able to retrieve logged-in user from http session

---

src/main/java/com/dvops/maven/eclipse/ProfileServlet.java
src/main/java/com/dvops/maven/eclipse/User.java
src/main/webapp/header.jsp
src/main/webapp/userprofile.jsp

- Created ProfileServlet to retrieve logged in username from session storage and query using username in database
- Created User.java which contains user class.
- This user class comprises of attributes (user info we want to display) along with its respective constructor, getters and setters.
- Ammended header.jsp so that it is able to navigate to updated url link which displays user information (/userprofile.jsp > /userprofile.jsp/ProfileServlet).

[feat](profile) Configured profile to display user information from database

---

src/main/java/GameServlet.java
src/main/java/com/dvops/maven/eclipse/ProfileServlet.java
src/main/java/com/dvops/maven/eclipse/User.java
src/main/webapp/WEB-INF/web.xml
src/main/webapp/gameById.jsp
src/main/webapp/header.jsp
src/main/webapp/reviewEdit.jsp
src/main/webapp/userprofile.jsp

- Added 2 methods showReview and updateReview in GameServlet.
- showReview opens up a form (reviewEdit.jsp) with existing information.
- updateReview updates the edited information.
- Configured web.xml file to define mappings between the URL paths and the servlets that handle requests with those paths.

[feat](game-review) Made editing of review functional with database

---

src/main/webapp/gameById.jsp

- an if condition has been added to compare the username stored inn the http storage to the specific review's username. This prevents other users from editing or deleting reviews that do not belong to them.
Signed-off-by: LetsGoRichard <richardaw13032001@gmail.com>

[feat](game-review): login to edit/delete reviews

---

src/main/java/com/dvops/maven/eclipse/LogoutServlet.java
src/main/webapp/header.jsp

- Created logout servlet.
- Added session.invalidate( ) in logout servlet which helps to clear current session.

[feat](logout) Made logout functional with logout servlet

---

src/main/webapp/gameById.jsp

- an if statement has been added to the gamebyid.jsp to check if the httpSession has a username stored. If no username is found, the "add a review button" will be hidden.
Signed-off-by: LetsGoRichard <richardaw13032001@gmail.com>

[feat](game-review): prevent non-account users from adding reviews

---

src/main/java/com/dvops/selenium_maven/eclipse/testng.xml

- Created testng.xml file. 
- This file allows us to create and handle multiple test classes by defining test suites and tests.
- Created new run configurations for automated testing and selected created testng.xml file as the test suite. 

[feat](selenium): Performed automated testing using created use cases and maven

---

src/main/webapp/index.jsp

continuous integration, delivery and deployment pipeline.
- added a comment to index.jsp for testing
Signed-off-by: LetsGoRichard <richardaw13032001@gmail.com>

[test](jenkins): updated index.jsp to test out jenkins

---

src/main/java/com/dvops/selenium_maven/eclipse/NewTest.java
src/main/webapp/gameById.jsp
src/main/webapp/login.jsp
src/main/webapp/register.jsp
src/main/webapp/reviewEdit.jsp

[test] Added test cases for login, register and adding review

---

src/main/webapp/gameById.jsp
src/main/webapp/login.jsp
src/main/webapp/register.jsp
src/main/webapp/reviewEdit.jsp

- Pages ammended include gameById.jsp, login.jsp, register.jsp and reviewEdit.jsp.

[fix] Configured all forms in website so user cannot leave fields blank

---

src/main/java/com/dvops/selenium_maven/eclipse/NewTest.java
src/main/webapp/gameById.jsp
src/main/webapp/gameManagement.jsp
src/main/webapp/header.jsp
src/main/webapp/reviewEdit.jsp

- Test cases include: addEditDeleteReview(), getGames(), getOneGame(), getReviews1(), getReviews2() & getProfile()

[test](selenium): Added in test cases for selenium

---

src/main/java/com/dvops/junit_maven/eclipse/Game.java
src/main/java/com/dvops/junit_maven/eclipse/GameCollection.java
src/main/java/com/dvops/junit_maven/eclipse/Reviews.java
src/main/java/com/dvops/junit_maven/eclipse/ReviewsCollection.java
src/main/java/com/dvops/junit_maven/eclipse/User.java
src/main/java/com/dvops/junit_maven/eclipse/UserCollection.java
src/test/java/com/dvops/junit_maven/eclipse/GameCollectionTest.java
src/test/java/com/dvops/junit_maven/eclipse/ReviewsCollectionTest.java
src/test/java/com/dvops/junit_maven/eclipse/UserCollectionTest.java

all functions for games and reviews have been implemented
Signed-off-by: LetsGoRichard <richardaw13032001@gmail.com>

[test](Junit): successful junit tests for games, review and user functions

---

pom.xml

[test](pom.xml): Added comment to test out automation of Jira

---

src/main/webapp/index.jsp

[test](jenkins) see if it builds successfully

---

src/main/java/com/dvops/selenium_maven/eclipse/NewTest.java

[test](selenium): Added in function to test out log out functionality

---

src/main/java/com/dvops/maven/eclipse/LoginServlet.java
src/main/java/com/dvops/selenium_maven/eclipse/NewTest.java

[test](selenium): Added test case in the event login fails

---

pom.xml

CM-96 Testing Jira Integration with Jira

---

pom.xml

CM-97 Testing GitHub integration with Jira (2)

---

pom.xml

CM-99 Integrating with GitHub (3)

---

pom.xml

CM-100 Integrating Jira with GitHub

---

pom.xml

CM-101 Testing integration of GitHub and Jira

---

pom.xml

CM-102 Integrating Jira with GitHub (6)

---

pom.xml

CM-103 Test out Jira integration with GitHub (7)

---

pom.xml

CM-104 Test out Jira integration with GitHub (8)

---

src/main/webapp/index.jsp

git commit -m "CM-105 <message>"

CM-105 git commit -m "CM-105 <message>"

---

pom.xml

CM-106 Test out Jira integration with GitHub 10

---

pom.xml

CM-107 Test out Jira integration with GitHub 11

---

pom.xml

[test](jenkins): Test whether jenkins is functional

---

pom.xml

[test](jenkins): Testing jenkinsFile functionality

---

pom.xml

[test](jenkins) Testing jenkinsFile

---

pom.xml

[test](jenkins): Testing jenkinsFile
